--CASE ... WHEN
-- CASE IS JUST USED FOR EQUAL TO 
--END SYNTAX WITH 'END'

DECLARE @DAY VARCHAR(50), @CASE_RES VARCHAR(50)
SET @DAY='MONDAY'
SET @CASE_RES = CASE @DAY
	WHEN 'MONDAY' THEN '22222'
	WHEN 'WENDESDAY' THEN '44444'
	ELSE 'NEVERMIND'
	END
	PRINT @CASE_RES


GO
DECLARE @DAY VARCHAR(50), @CASE_RES VARCHAR(50)
SET @DAY='WENDESDAY'
SET @CASE_RES = CASE @DAY
	WHEN 'MONDAY' THEN '22222'
	WHEN 'WENDESDAY' THEN '44444'
	WHEN 'WENDESDAY' THEN '3333333'
	END
	PRINT @CASE_RES

GO
DECLARE @DAY VARCHAR(50), @CASE_RES VARCHAR(50)
SET @DAY='THURSDAY'
SET @CASE_RES = CASE
	WHEN @DAY IN ('MONDAY','TUESDAY') THEN '2233'
	WHEN @DAY IN ('WENDESDAY','THURSDAY') THEN '4455'
	ELSE 'NEVERMIND'
	END
	PRINT @CASE_RES


GO 
DECLARE @NUM INT=20,@CASE_RES VARCHAR(20)
SET @CASE_RES= CASE
	WHEN @NUM<150 AND @NUM>100 THEN 'A'
	WHEN @NUM>30 AND @NUM<70 THEN 'B' 
	ELSE 'CHILD'
	END
PRINT @CASE_RES

--NUM 
-- <20 PRINT NUM *1.1
--100> NUM >21 *1.05
--NUM>101 *1.03
--PRINT
GO
DECLARE @NUM INT =90, @CASE_RES FLOAT
SET @CASE_RES= CASE
	WHEN @NUM>=101 THEN @NUM*1.03
	WHEN @NUM<=100 AND @NUM>=21 THEN @NUM*1.05
	WHEN @NUM>=20 THEN @NUM*1.1
	
	
END
PRINT @CASE_RES

SELECT 90*1.05

